# Generated by Django 4.2.2 on 2023-07-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_aboutmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='streetadres',
        ),
    ]
