# Generated by Django 4.2.2 on 2023-07-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_remove_aboutmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
