# Generated by Django 4.2.2 on 2023-07-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_commentmodel_email_commentmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='telephone',
        ),
    ]
