# Generated by Django 4.2.2 on 2023-10-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_alter_commentmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'About'},
        ),
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='tagcloudmodel',
            options={'verbose_name': 'Tag cloud'},
        ),
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='name',
            new_name='text',
        ),
    ]
